section_type: app
hidden: true
title: Centrum dowodzenia w kieszeni uczestnika
intro: |-
  Wspieramy wydarzenia naszą autorską aplikacją mobilną,
  która zwiększa zaangażowanie i ułatwia komunikację.
  To więcej niż agenda – to kompletne centrum dowodzenia Twojego eventu.
mockup_image: /images/app-mockup.png
features:
  - icon: message-circle
    title: Komunikacja w czasie rzeczywistym
    description: Push notifications, czat grupowy i prywatne wiadomości między uczestnikami.
  - icon: calendar
    title: Interaktywna agenda
    description: Spersonalizowana agenda z możliwością zapisywania ulubionych
      prezentacji i przypomnieniami.
  - icon: users
    title: Platform networking
    description: Łączenie uczestników o podobnych zainteresowaniach i ułatwianie
      nawiązywania kontaktów biznesowych.
cta_text: Zapytaj o aplikację dla Twojego eventu
cta_link: "#kontakt"
