title: "Aplikacja Event Manager"
intro: "Stworzyliśmy dedykowaną aplikację mobilną do zarządzania eventami, która pozwala organizatorom i uczestnikom na łatwą komunikację i koordynację wydarzeń."
mockup_image: "/images/app-mockup.png"
features:
  - icon: "calendar"
    title: "Harmonogram online"
    description: "Pełna kontrola nad agendą wydarzenia w czasie rzeczywistym"
  - icon: "users"
    title: "Zarządzanie gośćmi"
    description: "Lista gości, RSVP i komunikacja bezpośrednio przez aplikację"
  - icon: "mic"
    title: "Kontrola nagłośnienia"
    description: "Zdalne sterowanie systemem audio przez organizatorów"
  - icon: "bell"
    title: "Powiadomienia push"
    description: "Natychmiastowe informowanie o zmianach w programie"
cta_text: "Dowiedz się więcej"
cta_link: "#kontakt"
