site_name: kapitanie
site_description: Kompleksowa obsługa multimedialna eventów, konferencji i
  targów. Twój cel, nasza nawigacja. Perfekcyjne eventy.
company_name: kapitanie
company_description: Kompleksowa obsługa multimedialna eventów, koncertów i
  konferencji. Twój cel, nasza nawigacja. Perfekcyjne eventy.
email: kontakt@kapitanie.com
phone: "501181701"
address: ul. Różana 54B/1, 32-020 Wieliczka
nip: "5741597318"
social_media:
  show_social_media: false
  facebook: ""
  instagram: ""
  linkedin: ""
  youtube: ""
