site_name: kapitanie
site_description: Kompleksowa obsługa multimedialna eventów, koncertów i
  konferencji. Twoje wydarzenie w najlepszym świetle.
company_name: kapitanie
company_description: Kompleksowa obsługa multimedialna eventów, koncertów i konferencji. Twoje wydarzenie w najlepszym świetle.
email: przemo@kilan.com.pl
phone: "501181701"
address: Wieliczka 32-020, ul. Różana 54B/1
nip: "5741597318"
social_media:
  show_social_media: false
  facebook: ""
  instagram: ""
  linkedin: ""
  youtube: ""
