site_name: kapitanie
site_description: Kompleksowa obsługa multimedialna eventów, koncertów i
  konferencji. Twoje wydarzenie w najlepszym świetle. test
company_name: kapitanie
email: przemo@kilan.com.pl
phone: "501181705"
address: Wieliczka 32-020, ul. Różana 54B/2
nip: "5741597318"
social_media:
  show_social_media: false
  facebook: ""
  instagram: ""
  linkedin: ""
  youtube: ""
