# yaml-language-server: $schema=
# Site configuration for kapitanie website
company_name: "kapitanie"
tagline: "Tworzymy niezapomniane wydarzenia"
description: "Jesteśmy zespołem specjalistów od organizacji wydarzeń, który zamienia Twoje wizje w rzeczywistość. Od konferencji biznesowych po gale firmowe - każdy event realizujemy z pasją i dbałością o najdrobniejsze detale."
email: "kontakt@kapitanie.pl"
phone: "+48 123 456 789"
address: "ul. Eventowa 12, 00-001 Warszawa"
social:
  facebook: ""
  instagram: ""
  linkedin: ""
