# Site configuration for kapitanie website
site_name: "kapitanie"
site_description: "Jesteśmy kapitanami technicznej strony Twojego sukcesu. Zapewniamy kompleksową obsługę multimedialną eventów, koncertów i konferencji."
company_name: "kapitanie"
email: "kontakt@kapitanie.pl"
phone: "501181703"
address: "Wieliczka 32-020, ul. Różana 54B/1"
social_media:
  facebook: ""
  instagram: ""
  linkedin: ""
