backend:
  name: github
  repo: Przemmoo/kapitanie-website
  branch: main
  base_url: https://kapitanie-website.pages.dev
  auth_endpoint: /api/auth

# Uncomment for local development:
# local_backend: true

media_folder: "public/images"
public_folder: "/images"

# Site configuration
site_url: https://kapitanie-website.pages.dev
display_url: https://kapitanie-website.pages.dev
logo_url: https://kapitanie-website.pages.dev/favicon.svg

collections:
  - name: "realizacje"
    label: "Realizacje"
    label_singular: "Realizacja"
    folder: "src/content/realizacje"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{client}}"
    sortable_fields: ["date", "title", "client"]
    view_filters:
      - label: "Konferencje"
        field: category
        pattern: "Konferencja"
      - label: "Gale"
        field: category
        pattern: "Gala"
      - label: "Koncerty"
        field: category
        pattern: "Koncert"
      - label: "Eventy Firmowe"
        field: category
        pattern: "Event Firmowy"
    fields:
      - { label: "Tytuł", name: "title", widget: "string", hint: "Nazwa wydarzenia lub projektu" }
      - { label: "Klient", name: "client", widget: "string", hint: "Nazwa firmy lub organizatora" }
      - { label: "Data", name: "date", widget: "datetime", hint: "Data realizacji wydarzenia" }
      - { 
          label: "Kategoria", 
          name: "category", 
          widget: "select", 
          options: ["Konferencja", "Gala", "Koncert", "Event Firmowy"],
          hint: "Typ wydarzenia"
        }
      - { 
          label: "Zdjęcie główne", 
          name: "featured_image", 
          widget: "image", 
          required: false,
          hint: "Główne zdjęcie reprezentujące projekt"
        }
      - { 
          label: "Galeria zdjęć", 
          name: "gallery", 
          widget: "list",
          required: false,
          field: { label: "Zdjęcie", name: "image", widget: "image" },
          hint: "Dodatkowe zdjęcia z wydarzenia"
        }
      - { 
          label: "Opis", 
          name: "description", 
          widget: "text",
          hint: "Krótki opis projektu (1-2 zdania)"
        }
      - { 
          label: "Wyzwanie", 
          name: "challenge", 
          widget: "text",
          hint: "Jakie było główne wyzwanie tego projektu?"
        }
      - { 
          label: "Rozwiązanie", 
          name: "solution", 
          widget: "text",
          hint: "Jak rozwiązaliście to wyzwanie?"
        }
      - { 
          label: "Wyniki", 
          name: "results", 
          widget: "text", 
          required: false,
          hint: "Jakie były osiągnięte rezultaty? (opcjonalne)"
        }
      - { 
          label: "Treść", 
          name: "body", 
          widget: "markdown",
          hint: "Szczegółowy opis projektu w formacie Markdown"
        }

  - name: "ustawienia"
    label: "Ustawienia strony"
    files:
      - label: "Informacje o firmie"
        name: "site"
        file: "src/content/ustawienia/site.yaml"
        fields:
          - { 
              label: "Nazwa strony", 
              name: "site_name", 
              widget: "string", 
              default: "kapitanie",
              hint: "Nazwa wyświetlana w tytule strony"
            }
          - { 
              label: "Opis strony", 
              name: "site_description", 
              widget: "text",
              hint: "Opis strony dla SEO i social media"
            }
          - { 
              label: "Nazwa firmy", 
              name: "company_name", 
              widget: "string", 
              default: "kapitanie",
              hint: "Oficjalna nazwa firmy"
            }
          - { 
              label: "Email", 
              name: "email", 
              widget: "string", 
              pattern: ["^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", "Wprowadź poprawny adres email"],
              hint: "Główny adres email firmy"
            }
          - { 
              label: "Telefon", 
              name: "phone", 
              widget: "string",
              hint: "Numer telefonu kontaktowego"
            }
          - { 
              label: "Adres", 
              name: "address", 
              widget: "text",
              hint: "Pełny adres firmy"
            }
          - {
              label: "Social Media",
              name: "social_media",
              widget: "object",
              fields: [
                { label: "Facebook", name: "facebook", widget: "string", required: false },
                { label: "Instagram", name: "instagram", widget: "string", required: false },
                { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              ]
            }

  - name: "sekcje"
    label: "Sekcje strony"
    files:
      - label: "Sekcja Hero (Główna)"
        name: "hero"
        file: "src/content/sekcje/hero.yaml"
        fields:
          - { label: "Nagłówek główny", name: "title", widget: "string", hint: "Główny nagłówek na stronie" }
          - { label: "Podtytuł", name: "subtitle", widget: "text", hint: "Opis pod nagłówkiem" }
          - { label: "Tekst pierwszego przycisku", name: "cta1_text", widget: "string", default: "Zobacz nasze realizacje" }
          - { label: "Link pierwszego przycisku", name: "cta1_link", widget: "string", default: "#realizacje" }
          - { label: "Tekst drugiego przycisku", name: "cta2_text", widget: "string", default: "Skontaktuj się z nami" }
          - { label: "Link drugiego przycisku", name: "cta2_link", widget: "string", default: "#kontakt" }
          - { label: "Wideo tła (MP4)", name: "video_mp4", widget: "string", required: false, hint: "Ścieżka do wideo MP4" }
          - { label: "Wideo tła (WebM)", name: "video_webm", widget: "string", required: false, hint: "Ścieżka do wideo WebM" }
          - { label: "Zdjęcie zastępcze", name: "poster_image", widget: "image", required: false, hint: "Obraz wyświetlany gdy wideo się nie załaduje" }

      - label: "Sekcja O Nas"
        name: "about"
        file: "src/content/sekcje/about.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji O Nas" }
          - { label: "Opis główny", name: "description", widget: "text", hint: "Główny opis firmy" }
          - { label: "Zdjęcie zespołu", name: "team_image", widget: "image", required: false, hint: "Zdjęcie zespołu lub założyciela" }
          - { 
              label: "Filary oferty", 
              name: "pillars", 
              widget: "list",
              fields: [
                { label: "Ikona", name: "icon", widget: "string", hint: "Nazwa ikony (np. 'lightbulb', 'sound')" },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Opis", name: "description", widget: "text" }
              ]
            }
          - { 
              label: "Statystyki", 
              name: "stats", 
              widget: "list",
              fields: [
                { label: "Liczba", name: "number", widget: "string" },
                { label: "Opis", name: "label", widget: "string" }
              ]
            }

      - label: "Sekcja Aplikacja Eventowa"
        name: "app"
        file: "src/content/sekcje/app.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji aplikacji" }
          - { label: "Wprowadzenie", name: "intro", widget: "text", hint: "Krótki opis aplikacji" }
          - { label: "Mockup aplikacji", name: "mockup_image", widget: "image", required: false, hint: "Zdjęcie mockupu telefonu z aplikacją" }
          - { 
              label: "Funkcje aplikacji", 
              name: "features", 
              widget: "list",
              fields: [
                { label: "Ikona", name: "icon", widget: "string", hint: "Nazwa ikony" },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Opis", name: "description", widget: "text" }
              ]
            }
          - { label: "Tekst przycisku CTA", name: "cta_text", widget: "string", default: "Dowiedz się więcej" }
          - { label: "Link przycisku CTA", name: "cta_link", widget: "string", default: "#kontakt" }

      - label: "Sekcja Klienci"
        name: "clients"
        file: "src/content/sekcje/clients.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji klientów" }
          - { 
              label: "Logotypy klientów", 
              name: "client_logos", 
              widget: "list",
              fields: [
                { label: "Nazwa klienta", name: "name", widget: "string" },
                { label: "Logo", name: "logo", widget: "image" },
                { label: "Strona www", name: "website", widget: "string", required: false }
              ]
            }
          - { 
              label: "Testimoniale", 
              name: "testimonials", 
              widget: "list",
              fields: [
                { label: "Imię i nazwisko", name: "name", widget: "string" },
                { label: "Stanowisko", name: "position", widget: "string" },
                { label: "Firma", name: "company", widget: "string" },
                { label: "Opinia", name: "quote", widget: "text" },
                { label: "Zdjęcie", name: "photo", widget: "image", required: false },
                { label: "Ocena (1-5)", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5 }
              ]
            }
          - { 
              label: "Statystyki", 
              name: "stats", 
              widget: "list",
              fields: [
                { label: "Liczba", name: "number", widget: "string" },
                { label: "Opis", name: "label", widget: "string" }
              ]
            }

      - label: "Sekcja Kontakt"
        name: "contact"
        file: "src/content/sekcje/contact.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji kontaktowej" }
          - { label: "Podtytuł", name: "subtitle", widget: "text", hint: "Opis nad formularzem - użyj \\n dla nowych linii" }
          - { 
              label: "Metody kontaktu", 
              name: "contact_methods", 
              widget: "list",
              hint: "Lista wszystkich metod kontaktu włącznie z godzinami pracy i czasem odpowiedzi",
              fields: [
                { 
                  label: "Ikona", 
                  name: "icon", 
                  widget: "select",
                  options: ["phone", "mail", "map-pin", "clock", "timer"],
                  hint: "phone (telefon), mail (email), map-pin (adres), clock (godziny pracy), timer (czas odpowiedzi)"
                },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Wartość", name: "value", widget: "string" },
                { label: "Link", name: "link", widget: "string", required: false, hint: "Opcjonalny link (tel:, mailto:, https:)" }
              ]
            }

  - name: "podstrony"
    label: "Podstrony"
    files:
      - label: "Polityka Prywatności"
        name: "privacy"
        file: "src/content/podstrony/privacy.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Polityka Prywatności" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Data ostatniej aktualizacji", name: "last_updated", widget: "datetime" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść polityki prywatności" }

      - label: "Polityka Cookies"
        name: "cookies"
        file: "src/content/podstrony/cookies.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Polityka Cookies" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Data ostatniej aktualizacji", name: "last_updated", widget: "datetime" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść polityki cookies" }

      - label: "Regulamin"
        name: "terms"
        file: "src/content/podstrony/terms.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Regulamin" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Data ostatniej aktualizacji", name: "last_updated", widget: "datetime" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść regulaminu" }
