backend:
  name: github
  repo: Przemmoo/kapitanie-website
  branch: main
  base_url: https://kapitanie.com
  auth_endpoint: /api/auth

# Uncomment for local development:
# local_backend: true

media_folder: "public/images"
public_folder: "/images"

# Site configuration
site_url: https://kapitanie.com
display_url: https://kapitanie.com
logo_url: https://kapitanie.com/favicon.svg

collections:
  # Sekcje strony w kolejności wyświetlania
  - label: "Sekcja Hero (Główna)"
    name: "hero"
    files:
      - label: "Ustawienia sekcji Hero"
        name: "hero"
        file: "src/content/sekcje/hero.yaml"
        fields:
          - { label: "Nagłówek główny", name: "title", widget: "string", hint: "Główny nagłówek na stronie" }
          - { label: "Podtytuł", name: "subtitle", widget: "text", hint: "Opis pod nagłówkiem" }
          - { label: "Tekst pierwszego przycisku", name: "cta1_text", widget: "string", default: "Zobacz nasze realizacje" }
          - { label: "Link pierwszego przycisku", name: "cta1_link", widget: "string", default: "#realizacje" }
          - { label: "Tekst drugiego przycisku", name: "cta2_text", widget: "string", default: "Skontaktuj się z nami" }
          - { label: "Link drugiego przycisku", name: "cta2_link", widget: "string", default: "#kontakt" }
          - { label: "Wideo tła (MP4)", name: "video_mp4", widget: "string", required: false, hint: "Ścieżka do wideo MP4" }
          - { label: "Wideo tła (WebM)", name: "video_webm", widget: "string", required: false, hint: "Ścieżka do wideo WebM" }
          - { label: "Zdjęcie zastępcze", name: "poster_image", widget: "image", required: false, hint: "Obraz wyświetlany gdy wideo się nie załaduje" }

  - label: "Sekcja O Nas"
    name: "about"
    files:
      - label: "Ustawienia sekcji O Nas"
        name: "about"
        file: "src/content/sekcje/about.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji O Nas" }
          - { label: "Opis główny", name: "description", widget: "text", hint: "Główny opis firmy" }
          # Usunięto pole 'Zdjęcie zespołu' (team_image) jako niepotrzebne
          - { 
              label: "Filary oferty", 
              name: "pillars", 
              widget: "list",
              fields: [
                { label: "Ikona", name: "icon", widget: "string", hint: "Nazwa ikony z Lucide Icons (np. lightbulb, mic, monitor, audio-lines, heart, star, settings). Zobacz pełną listę: https://lucide.dev/icons/" },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Opis", name: "description", widget: "text" },
                { label: "Treść (markdown)", name: "content", widget: "markdown", hint: "Szczegółowa treść filaru, obsługuje markdown. Wyświetlana po kliknięciu w filar." }
              ]
            }
          - { 
              label: "Statystyki", 
              name: "stats", 
              widget: "list",
              fields: [
                { label: "Liczba", name: "number", widget: "string" },
                { label: "Opis", name: "label", widget: "string" }
              ]
            }

  # Kategorie realizacji
  - name: "kategorie-realizacji"
    label: "Kategorie Realizacji"
    label_singular: "Kategoria"
    folder: "src/content/kategorie-realizacji"
    create: true
    slug: "{{slug}}"
    summary: "{{name}}"
    sortable_fields: ["order", "name"]
    fields:
      - { label: "Nazwa", name: "name", widget: "string", hint: "Nazwa kategorii" }
      - { label: "Opis", name: "description", widget: "text", hint: "Krótki opis kategorii" }
      - { label: "Kolejność", name: "order", widget: "number", hint: "Kolejność wyświetlania (1, 2, 3...)" }
      - { label: "Kolor", name: "color", widget: "color", required: false, hint: "Kolor przypisany do kategorii" }
      - { label: "Ikona", name: "icon", widget: "string", required: false, hint: "Nazwa ikony (np. microphone, users)" }
      - { label: "Aktywna", name: "active", widget: "boolean", default: true, hint: "Czy kategoria ma być widoczna na stronie" }
      - { label: "Treść", name: "body", widget: "markdown", hint: "Szczegółowy opis kategorii" }

  - name: "realizacje"
    label: "Sekcja Realizacje"
    label_singular: "Realizacja"
    folder: "src/content/realizacje"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{client}}"
    sortable_fields: ["date", "title", "client", "category"]
    view_filters:
      - label: "Konferencje"
        field: category
        pattern: "Konferencje"
      - label: "Gale Firmowe"
        field: category
        pattern: "Gale Firmowe"
      - label: "Koncerty"
        field: category
        pattern: "Koncerty"
      - label: "Eventy Korporacyjne"
        field: category
        pattern: "Eventy Korporacyjne"
      - label: "Wyróżnione"
        field: featured
        pattern: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string", hint: "Nazwa wydarzenia lub projektu" }
      - { label: "Klient", name: "client", widget: "string", hint: "Nazwa firmy lub organizatora" }
      - { label: "Data", name: "date", widget: "datetime", hint: "Data realizacji wydarzenia" }
      - { 
          label: "Kategoria", 
          name: "category", 
          widget: "select",
          options: ["Konferencje", "Gale Firmowe", "Koncerty", "Eventy Korporacyjne"],
          hint: "Wybierz kategorię z listy dostępnych"
        }
      - { label: "Wyróżniony projekt", name: "featured", widget: "boolean", required: false, default: false, hint: "Czy projekt ma być wyróżniony na stronie głównej" }
      - { 
          label: "Tagi", 
          name: "tags", 
          widget: "list",
          required: false,
          hint: "Słowa kluczowe opisujące projekt (np. streaming, oświetlenie LED, hybrid)"
        }
      - { 
          label: "Zdjęcie główne", 
          name: "featured_image", 
          widget: "image", 
          required: false,
          hint: "Główne zdjęcie reprezentujące projekt"
        }
      - { 
          label: "Galeria zdjęć", 
          name: "gallery", 
          widget: "list",
          required: false,
          field: { label: "Zdjęcie", name: "image", widget: "image" },
          hint: "Dodatkowe zdjęcia z wydarzenia"
        }
      - { 
          label: "Opis", 
          name: "description", 
          widget: "markdown",
          hint: "Krótki opis projektu (1-2 zdania)"
        }
      - { 
          label: "Wyzwanie", 
          name: "challenge", 
          widget: "text",
          hint: "Jakie było główne wyzwanie tego projektu?"
        }
      - { 
          label: "Rozwiązanie", 
          name: "solution", 
          widget: "text",
          hint: "Jak rozwiązaliście to wyzwanie?"
        }

  - label: "Sekcja Aplikacja Eventowa"
    name: "app"
    files:
      - label: "Ustawienia sekcji Aplikacja"
        name: "app"
        file: "src/content/sekcje/app.yaml"
        fields:
          - { label: "Ukryj sekcję", name: "hidden", widget: "boolean", default: false, hint: "Zaznacz aby ukryć całą sekcję" }
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji aplikacji" }
          - { label: "Wprowadzenie", name: "intro", widget: "text", hint: "Krótki opis aplikacji" }
          - { label: "Mockup aplikacji", name: "mockup_image", widget: "image", required: false, hint: "Zdjęcie mockupu telefonu z aplikacją" }
          - { 
              label: "Funkcje aplikacji", 
              name: "features", 
              widget: "list",
              fields: [
                { label: "Ikona", name: "icon", widget: "string", hint: "Nazwa ikony z Lucide Icons (np. message-circle, calendar, users, phone, heart). Zobacz pełną listę: https://lucide.dev/icons/" },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Opis", name: "description", widget: "text" }
              ]
            }
          - { label: "Tekst przycisku CTA", name: "cta_text", widget: "string", default: "Dowiedz się więcej" }
          - { label: "Link przycisku CTA", name: "cta_link", widget: "string", default: "#kontakt" }

  - label: "Sekcja Klienci"
    name: "clients"
    files:
      - label: "Ustawienia sekcji Klienci"
        name: "clients"
        file: "src/content/sekcje/clients.yaml"
        fields:
          - { label: "Ukryj sekcję", name: "hidden", widget: "boolean", default: false, hint: "Zaznacz aby ukryć całą sekcję" }
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji klientów" }
          - { label: "Podtytuł", name: "subtitle", widget: "text", hint: "Opis pod tytułem sekcji", required: false }
          - { 
              label: "Statystyki", 
              name: "stats", 
              widget: "list",
              fields: [
                { label: "Liczba", name: "number", widget: "string" },
                { label: "Opis", name: "label", widget: "string" }
              ]
            }
          - { 
              label: "Logotypy klientów", 
              name: "client_logos", 
              widget: "list",
              fields: [
                { label: "Nazwa klienta", name: "name", widget: "string" },
                { label: "Logo", name: "logo", widget: "image" },
                { label: "Strona www", name: "website", widget: "string", required: false }
              ]
            }
          - { label: "Ukryj testimoniale", name: "hide_testimonials", widget: "boolean", default: false, hint: "Zaznacz aby ukryć sekcję testimoniali" }
          - { 
              label: "Testimoniale", 
              name: "testimonials", 
              widget: "list",
              fields: [
                { label: "Imię i nazwisko", name: "name", widget: "string" },
                { label: "Stanowisko", name: "position", widget: "string" },
                { label: "Firma", name: "company", widget: "string" },
                { label: "Opinia", name: "quote", widget: "text" },
                { label: "Zdjęcie", name: "photo", widget: "image", required: false },
                { label: "Ocena (1-5)", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5 }
              ]
            }

  - label: "Sekcja Kontakt"
    name: "contact"
    files:
      - label: "Ustawienia sekcji Kontakt"
        name: "contact"
        file: "src/content/sekcje/contact.yaml"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string", hint: "Tytuł sekcji kontaktowej" }
          - { label: "Podtytuł", name: "subtitle", widget: "text", hint: "Opis nad formularzem - użyj \\n dla nowych linii" }
          - { 
              label: "Metody kontaktu", 
              name: "contact_methods", 
              widget: "list",
              hint: "Lista wszystkich metod kontaktu włącznie z godzinami pracy i czasem odpowiedzi",
              fields: [
                { 
                  label: "Ikona", 
                  name: "icon", 
                  widget: "string",
                  hint: "Nazwa ikony z Lucide Icons (np. phone, mail, map-pin, clock, timer, home, settings). Zobacz pełną listę: https://lucide.dev/icons/"
                },
                { label: "Tytuł", name: "title", widget: "string" },
                { label: "Wartość", name: "value", widget: "string" },
                { label: "Link", name: "link", widget: "string", required: false, hint: "Opcjonalny link (tel:, mailto:, https:)" }
              ]
            }

  - label: "Sekcja Footer"
    name: "site"
    files:
      - label: "Ustawienia footera"
        name: "site"
        file: "src/content/ustawienia/site.yaml"
        fields:
          - { 
              label: "Nazwa strony", 
              name: "site_name", 
              widget: "string", 
              default: "kapitanie",
              hint: "Nazwa wyświetlana w tytule strony"
            }
          - { 
              label: "Opis strony", 
              name: "site_description", 
              widget: "text",
              hint: "Opis strony dla SEO i social media"
            }
          - { 
              label: "Nazwa firmy", 
              name: "company_name", 
              widget: "string", 
              default: "kapitanie",
              hint: "Oficjalna nazwa firmy"
            }
          - { 
              label: "Opis firmy", 
              name: "company_description", 
              widget: "text",
              hint: "Krótki opis firmy wyświetlany w footerze"
            }
          - { 
              label: "Email", 
              name: "email", 
              widget: "string", 
              pattern: ["^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", "Wprowadź poprawny adres email"],
              hint: "Główny adres email firmy"
            }
          - { 
              label: "Telefon", 
              name: "phone", 
              widget: "string",
              hint: "Numer telefonu kontaktowego"
            }
          - { 
              label: "Adres", 
              name: "address", 
              widget: "text",
              hint: "Pełny adres firmy"
            }
          - { 
              label: "NIP", 
              name: "nip", 
              widget: "string",
              required: false,
              hint: "Numer identyfikacji podatkowej firmy"
            }
          - {
              label: "Social Media",
              name: "social_media",
              widget: "object",
              fields: [
                { label: "Pokaż sekcję Social Media", name: "show_social_media", widget: "boolean", default: true, hint: "Włącz/wyłącz wyświetlanie sekcji social media w footerze" },
                { label: "Facebook", name: "facebook", widget: "string", required: false, hint: "Link do profilu Facebook (pełny URL)" },
                { label: "Instagram", name: "instagram", widget: "string", required: false, hint: "Link do profilu Instagram (pełny URL)" },
                { label: "LinkedIn", name: "linkedin", widget: "string", required: false, hint: "Link do profilu LinkedIn (pełny URL)" },
                { label: "YouTube", name: "youtube", widget: "string", required: false, hint: "Link do kanału YouTube (pełny URL)" }
              ]
            }

  - name: "podstrony"
    label: "Podstrony"
    files:
      - label: "Polityka Prywatności"
        name: "privacy"
        file: "src/content/podstrony/privacy.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Polityka Prywatności" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść polityki prywatności" }

      - label: "Polityka Cookies"
        name: "cookies"
        file: "src/content/podstrony/cookies.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Polityka Cookies" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść polityki cookies" }

      - label: "Regulamin"
        name: "terms"
        file: "src/content/podstrony/terms.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "Regulamin" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść regulaminu" }

      - label: "RODO/GDPR"
        name: "rodo"
        file: "src/content/podstrony/rodo.yaml"
        fields:
          - { label: "Tytuł", name: "title", widget: "string", default: "RODO/GDPR" }
          - { label: "Opis SEO", name: "description", widget: "text" }
          - { label: "Treść", name: "content", widget: "markdown", hint: "Treść przepisów RODO/GDPR" }

  - label: "Header (Nawigacja)"
    name: "header"
    files:
      - label: "Ustawienia nagłówka (Header)"
        name: "header"
        file: "src/content/header/header.yaml"
        fields:
          - { label: "Logotyp", name: "logo", widget: "image", required: false, hint: "Logo wyświetlane w nagłówku" }
          - { label: "Tekst logotypu", name: "logo_text", widget: "string", default: "kapitanie", hint: "Tekst obok logotypu" }
          - { label: "Menu nawigacyjne", name: "nav", widget: "list", summary: "{{label}} ({{link}})", fields: [
              { label: "Etykieta", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string", hint: "np. #o-nas, #realizacje, /kontakt" }
            ] }
          - { label: "Pokaż CTA (Wyceń Projekt)", name: "show_cta", widget: "boolean", default: true, hint: "Czy wyświetlać przycisk CTA w menu" }
          - { label: "Tekst CTA", name: "cta_text", widget: "string", default: "Wyceń Projekt", required: false }
          - { label: "Link CTA", name: "cta_link", widget: "string", default: "#kontakt", required: false }
