backend:
  name: github
  repo: Przemmoo/kapitanie-website
  branch: main
  site_domain: kapitanie-website.pages.dev
  base_url: https://kapitanie-website.pages.dev
  auth_endpoint: api/auth

# Uncomment for local development:
# local_backend: true

# local_backend: true  # Wyłączone dla produkcji - użyj npx @decaporg/decap-server dla lokalnego developmentu

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "realizacje"
    label: "Realizacje"
    folder: "src/content/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Klient", name: "client", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Kategoria", name: "category", widget: "select", options: ["Konferencja", "Gala", "Koncert", "Event Firmowy"] }
      - { label: "Zdjęcie główne", name: "featured_image", widget: "image", required: false }
      - { label: "Opis", name: "description", widget: "markdown" }
      - { label: "Wyzwanie", name: "challenge", widget: "text" }
      - { label: "Rozwiązanie", name: "solution", widget: "text" }
      - { label: "Wyniki", name: "results", widget: "text", required: false }

  - name: "ustawienia"
    label: "Ustawienia strony"
    files:
      - label: "Informacje o firmie"
        name: "site"
        file: "src/content/ustawienia/site.yaml"
        fields:
          - { label: "Nazwa firmy", name: "company_name", widget: "string" }
          - { label: "Slogan", name: "tagline", widget: "string" }
          - { label: "Opis firmy", name: "description", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "Adres", name: "address", widget: "text" }
