backend:
  name: github
  repo: Przemmoo/kapitanie-website
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'
    openAuthoring: '{{message}}'

local_backend: true
media_folder: "src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "realizacje"
    label: "Realizacje"
    folder: "src/content/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Klient", name: "client", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Kategoria", name: "category", widget: "select", options: ["Konferencja", "Gala", "Koncert", "Event Firmowy"] }
      - { label: "Zdjęcie główne", name: "featured_image", widget: "image" }
      - { label: "Galeria", name: "gallery", widget: "list", field: { label: "Zdjęcie", name: "image", widget: "image" } }
      - { label: "Opis", name: "description", widget: "markdown" }
      - { label: "Wyzwanie", name: "challenge", widget: "text" }
      - { label: "Rozwiązanie", name: "solution", widget: "text" }
      - { label: "Wyniki", name: "results", widget: "text", required: false }

  - name: "ustawienia"
    label: "Ustawienia strony"
    files:
      - label: "Informacje o firmie"
        name: "site"
        file: "src/content/ustawienia/site.yaml"
        fields:
          - { label: "Nazwa firmy", name: "company_name", widget: "string" }
          - { label: "Slogan", name: "tagline", widget: "string" }
          - { label: "Opis firmy", name: "description", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "Adres", name: "address", widget: "text" }
          - { label: "Social Media", name: "social", widget: "object", fields: [
              { label: "Facebook", name: "facebook", widget: "string", required: false },
              { label: "Instagram", name: "instagram", widget: "string", required: false },
              { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
            ]}
